Add: Simplified Chinese Translation
ampersand38/amp pull request #2
Opened 2020-06-24 09:10 UTC by GoldJohnKing

Add: Simplified Chinese Translation

**When merged this pull request will:**
- Add: Simplified Chinese Translation

2020-06-24 13:05 UTC, ampersand38 requested changes

2020-06-24 13:05 UTC, ampersand38 commented on addons/slingload/stringtable.xml
> +            <Chinesesimp>自动安装吊钩</Chinesesimp>
Should be Manual or Custom

2020-06-24 13:05 UTC, ampersand38 commented on addons/slingload/stringtable.xml
> +            <Chinesesimp>安装吊钩</Chinesesimp>
Maybe 准备吊挂?

2020-06-25 00:10 UTC, GoldJohnKing commented on addons/slingload/stringtable.xml
> +            <Chinesesimp>自动安装吊钩</Chinesesimp>
Yes.

2020-06-25 00:11 UTC, GoldJohnKing commented on addons/slingload/stringtable.xml
> +            <Chinesesimp>安装吊钩</Chinesesimp>
I've got a better translation for this.

2020-06-25 03:21 UTC, ampersand38 approved these changes

2020-06-25 03:23 UTC, merged